### ISSUE TITLE
OBV(**)和MAOBV是什么区别？

### ISSUE THREAD

**Issue by smcduck** [idoall/TokenExchangeCommon#1]
很多画图工具中提供了两个OBV的相关指标，一个叫OBV(30),30可以改，一个叫MAOBV。

我找了很多资料，一直没搞明白它们之间计算方式的区别。

**Comment by idoall** [comment]
OBV能量潮指标是由两条线组成的，第一条线为MAOBV线，一般情况下，MAOBV线主要是依据30天内的成交量来计算出的OBV指标的简单移动平均线。换句话说，MAOBV线其实就是指OBV指标的30天的平均量的线。

**Comment by smcduck** [comment]
是这样理解吗？

OBV(30) = OBV(AVG(inReal))       // AVG(inReal, 30)指对原始数据做30天平均

MAOBV(30) = SMA(OBV(30), 30)
